-- MySQL Script generated by MySQL Workbench
-- 07/20/18 16:01:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema selfizeeV2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `selfizeeV2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `selfizeeV2` ;

-- -----------------------------------------------------
-- Table `selfizeeV2`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`evenements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`evenements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `is_marque_blanche` TINYINT(1) NULL,
  `is_data_acces` TINYINT(1) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evenements_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_evenements_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `selfizeeV2`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`galeries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`galeries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL,
  `is_public` VARCHAR(45) NULL,
  `titre` VARCHAR(255) NULL,
  `sous_titre` VARCHAR(255) NULL,
  `couleur` VARCHAR(45) NULL,
  `img_banniere` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `role_id` INT NOT NULL,
  `evenement_id` INT NULL,
  `galerie_id` INT NULL,
  `client_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`role_id` ASC),
  INDEX `fk_users_evenements1_idx` (`evenement_id` ASC),
  INDEX `fk_users_galeries1_idx` (`galerie_id` ASC),
  INDEX `fk_users_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `selfizeeV2`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_galeries1`
    FOREIGN KEY (`galerie_id`)
    REFERENCES `selfizeeV2`.`galeries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `selfizeeV2`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`galeries_has_evenements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`galeries_has_evenements` (
  `galerie_id` INT NOT NULL,
  `evenements_id` INT NOT NULL,
  PRIMARY KEY (`galerie_id`, `evenements_id`),
  INDEX `fk_galeries_has_evenements_evenements1_idx` (`evenements_id` ASC),
  INDEX `fk_galeries_has_evenements_galeries1_idx` (`galerie_id` ASC),
  CONSTRAINT `fk_galeries_has_evenements_galeries1`
    FOREIGN KEY (`galerie_id`)
    REFERENCES `selfizeeV2`.`galeries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_galeries_has_evenements_evenements1`
    FOREIGN KEY (`evenements_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`page_souvenirs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`page_souvenirs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `couleur_fond_entete` VARCHAR(45) NULL,
  `couleur_fond` VARCHAR(45) NULL,
  `img_banniere` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evenement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_page_souvenirs_evenements1_idx` (`evenement_id` ASC),
  CONSTRAINT `fk_page_souvenirs_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`email_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`email_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email_expediteur` VARCHAR(250) NULL,
  `nom_expediteur` VARCHAR(250) NULL,
  `objet` TEXT NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  `is_photo_en_pj` TINYINT(1) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evenement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_configurations_evenements1_idx` (`evenement_id` ASC),
  CONSTRAINT `fk_email_configurations_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`sms_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`sms_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expediteur` VARCHAR(250) NOT NULL,
  `contenu` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evenement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sms_configurations_evenements1_idx` (`evenement_id` ASC),
  CONSTRAINT `fk_sms_configurations_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`rs_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`rs_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc_facebook` TEXT NULL,
  `desc_twiter` TEXT NULL,
  `hashtag_twitter` VARCHAR(250) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evenement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rs_configurations_evenements1_idx` (`evenement_id` ASC),
  CONSTRAINT `fk_rs_configurations_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_origne` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `is_postable_on_facebook` TINYINT(1) NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `evenement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photos_evenements1_idx` (`evenement_id` ASC),
  CONSTRAINT `fk_photos_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `telephone` VARCHAR(255) NULL,
  `code_pays` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `photo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_photos1_idx` (`photo_id` ASC),
  CONSTRAINT `fk_contacts_photos1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `selfizeeV2`.`photos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`intervalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`intervalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intervalle` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selfizeeV2`.`crons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `selfizeeV2`.`crons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_active` TINYINT(1) NOT NULL,
  `is_cron_email` TINYINT(1) NOT NULL,
  `is_cron_sms` TINYINT(1) NOT NULL,
  `date_debut` DATETIME NOT NULL,
  `date_fin` DATETIME NOT NULL,
  `evenement_id` INT NOT NULL,
  `intervalle_id` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crons_evenements1_idx` (`evenement_id` ASC),
  INDEX `fk_crons_intervalles1_idx` (`intervalle_id` ASC),
  CONSTRAINT `fk_crons_evenements1`
    FOREIGN KEY (`evenement_id`)
    REFERENCES `selfizeeV2`.`evenements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crons_intervalles1`
    FOREIGN KEY (`intervalle_id`)
    REFERENCES `selfizeeV2`.`intervalles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
