CREATE TABLE `evenement_stat_campaigns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `evenement_id` int(11) NOT NULL,
  `event_click_delay` varchar(250) DEFAULT NULL,
  `event_clicked_count` int(11) DEFAULT NULL,
  `event_open_delay` varchar(250) DEFAULT NULL,
  `event_opened_count` int(11) DEFAULT NULL,
  `event_spam_count` int(11) DEFAULT NULL,
  `event_unsubscribed_count` int(11) DEFAULT NULL,
  `event_workflow_exited_count` int(11) DEFAULT NULL,
  `message_blocked_count` int(11) DEFAULT NULL,
  `message_clicked_count` int(11) DEFAULT NULL,
  `message_deferred_count` int(11) DEFAULT NULL,
  `message_hard_bounced_count` int(11) DEFAULT NULL,
  `message_opened_count` int(11) DEFAULT NULL,
  `message_queued_count` int(11) DEFAULT NULL,
  `message_sent_count` int(11) DEFAULT NULL,
  `message_soft_bounced_count` int(11) DEFAULT NULL,
  `message_spam_count` int(11) DEFAULT NULL,
  `message_unsubscribed_count` int(11) DEFAULT NULL,
  `message_workflow_exited_count` int(11) DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `total` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_evenement_stat_campaigns` (`evenement_id`),
  CONSTRAINT `FK_evenement_stat_campaigns` FOREIGN KEY (`evenement_id`) REFERENCES `evenements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
