
INSERT INTO `rs_configurations` (`desc_facebook`, `hashtag_twitter`, `desc_twiter`, `evenement_id`) VALUES
('', '', '', 25),
('', '', '', 28),
('', '', '', 29),
('', '', '', 30),
('', '', '', 31),
('', '', '', 34),
('', '', '', 35),
('', '', '', 38),
('', '', '', 39),
('', '', '', 40),
('', '', '', 41),
('', '', '', 42),
('', '', '', 43),
('', '', '', 44),
('', '', '', 45),
('', '', '', 47),
('', '', '', 48),
('', '', '', 50),
('', '', '', 51),
('', '', '', 53),
('', '', '', 54),
('', '', '', 55),
('', '', '', 56),
('', '', '', 57),
('', '', '', 58),
('', '', '', 59),
('', '', '', 60),
('', '', '', 61),
('', '', '', 63),
('', '', '', 66),
('', '', '', 67),
('', '', '', 68),
('', '', '', 70),
('', '', '', 71),
('', '', '', 72),
('', '', '', 73),
('', '', '', 74),
('', '', '', 75),
('', '', '', 76),
('', '', '', 77),
('', '', '', 78),
('', '', '', 79),
('', '', '', 80),
('', '', '', 81),
('', '', '', 82),
('', '', '', 83),
('', '', '', 84),
('', '', '', 85),
('', '', '', 86),
('', '', '', 87),
('', '', '', 88),
('', '', '', 89),
('', '', '', 90),
('', '', '', 91),
('', '', '', 92),
('', '', '', 93),
('', '', '', 94),
('', '', '', 95),
('', '', '', 101),
('', '', '', 102),
('', '', '', 103),
('', '', '', 104),
('', '', '', 105),
('', '', '', 106),
('', '', '', 107),
('', '', '', 108),
('', '', '', 109),
('', '', '', 110),
('', '', '', 111),
('', '', '', 113),
('', '', '', 114),
('', '', '', 115),
('', '', '', 116),
('', '', '', 117),
('', '', '', 118),
('', '', '', 119),
('', '', '', 120),
('', '', '', 121),
('', '', '', 122),
('19ème édition du Tournoi Révélateur de Talent, le Tournoi Européen U21 !', '', 'Ma photo prise lors du Tournoi Européen U21 !', 123),
('', '', '', 124),
('', '', '', 126),
('', '', '', 128),
('Photo souvenir de la soirée Dîner en Blanc du samedi 24 août organisée par Saint-Brieuc Entreprises', 'sbe, st-brieuc, soirée', 'Photo souvenir de la soirée Dîner en Blanc à St-Brieuc', 129),
('', '', '', 130),
('Photo from Jumbo Food Markt with Tussock Jumper', '', 'My photo from Jumbo Food Markt', 131),
('', '', '', 132),
('Photo souvenir du SPACE 2016 / Photo from SPACE 2016 ', 'Space', 'Photo souvenir du SPACE 2016', 133),
('Ma photo souvenir du Cordon Open Golf à Pléneuf Val-André avec les Gîtes de France', '', 'Ma photo souvenir du Cordon Open Golf', 134),
('', '', '', 135),
('', '', '', 136),
('', '', '', 137),
('', '', '', 138),
('', '', '', 139),
('', '', '', 140),
('Photo souvenir SDAEC TERRALIANCE lors du SPACE 2016', 'space', 'photo souvenir du SDAEC TERRALIANCE au SPACE 2016', 141),
('', '', '', 142),
('Photo souvenir du SPACE 2016 / Photo from SPACE 2016 ', 'space2016', 'Photo souvenir du SPACE 2016', 143),
('Photo souvenir des 8 ans du VandB Langueux le 17 septembre 2016 !  ', 'VandB, anniversaire', 'Photo souvenir des 8ans du VandB Langueux', 144),
('', '', '', 145),
('', '', '', 146),
('Photo souvenir de l\'inauguration de MAZE BSA Plouisy 21 au 24 septembre 2016', '', 'Photo souvenir inauguration MAZE BSA Plouisy', 147),
('Photo souvenir de l\'inauguration du MAZE BSA à Plouisy, du 21 au 24 septembre 2016 ', '', 'Photo souvenir de l\'inauguration du MAZE BSA à Plouisy ', 148),
('Photo souvenir de l\'inauguration du MAZE BSA à Plouisy, du 21 au 24 septembre 2016 ', '', 'Photo souvenir de l\'inauguration du MAZE BSA à Plouisy ', 149),
('Photo souvenir de l\'inauguration du MAZE BSA à Plouisy, du 21 au 24 septembre 2016 ', '', 'Photo souvenir de l\'inauguration du MAZE BSA à Plouisy ', 150),
('Photo souvenir de l\'inauguration du MAZE BSA à Plouisy, du 21 au 24 septembre 2016 ', '', 'Photo souvenir de l\'inauguration du MAZE BSA à Plouisy ', 151),
('Photo souvenir de l\'inauguration des nouveaux bâtiments du Cabinet JF Meheust, le 23 septembre 2016', '', 'Photo souvenir soirée d\'inauguration du Cabinet JF Meheust', 152),
('Photo souvenir de l\'inauguration des bâtiments du cabinet JF Meheust, le 23 septembre 2016 à Plérin', '', 'Photo souvenir de l\'inauguration des bâtiments du cabinet JF Meheust', 154),
('', '', '', 155),
('', '', '', 156),
('Photo souvenir de l\'inauguration du nouveau magasin CDJ FACTORY en partenariat avec le MINI STORE Langueux', 'CDJ, MINI', 'Photo souvenir de l\'inauguration du nouveau magasin CDJ FACTORY ', 157),
('Photo souvenir du salon professionnel Auto Distribution Armorique du 13 octobre 2016 à Ploufragan', 'AD, selfie', 'photo souvenir inauguration salon AD Armorique ', 158),
('', '', '', 159),
('', '', '', 160),
('', '', '', 162),
('', '', '', 163),
('', '', '', 164),
('', '', '', 165),
('', '', '', 166),
('', '', '', 167),
('', '', '', 168),
('', '', '', 169),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail', 'photo souvenir du salon du trail au templiers', 173),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 174),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 175),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 176),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 177),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 178),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 179),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 180),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 181),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 182),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 183),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 184),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 185),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 186),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 187),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 188),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 189),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 190),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 191),
('Photo souvenir prise lors du salon du trail au festival des Templiers 2016', 'templiers,trail, salon', 'photo souvenir du salon du trail au templiers', 192),
('', '', '', 193),
('', '', '', 194),
('', '', '', 195),
('Photo souvenir de la soirée d\'inauguration du DEL ARTE LYON du 2 octobre 2016 ', 'inauguration, Del Arte, Lyon, Selfizee', 'Photo souvenir de la soirée d\'inauguration du DEL ARTE LYON', 196),
('Photo souvenir de la soirée de lancement du nouveau 3008 le 3 novembre à Peugeot Chambéry', 'Peugeot, 3008, selfie', 'Photo souvenir de la soirée de lancement du nouveau 3008 ', 197),
('', '', '', 198),
('', '', '', 199),
('Photo souvenir de l\'événement Facom Show de Auto Pièces Atlantique - Carmoine du 17 novembre 2016 à Orvault', 'selfie, Auto Pièces Atlantique', 'Photo souvenir du Facom Show avec Auto Pièces Atlantique', 200),
('', '', '', 201),
('', '', '', 203),
('', '', '', 204),
('', '', '', 205),
('Photo souvenir de la soirée des 4 ans du VandB Annecy le 26 novembre 2016', 'VandB, annecy, selfizee', 'Photo souvenir des 4 ans du VandB Annecy', 206),
('Photo souvenir prise lors de l\'inauguration du VandB Rennes sud-est du 1er décembre ! ', 'V&b, inauguration, selfizee, rennes', 'Photo souvenir de l\'inauguration du VandB Rennes sud-est', 207),
('Photo prise durant la SOIRÉE CINÉMA du 1er Décembre 2016', '', 'SOIRÉE_CINÉMA_2016', 208),
('Photo souvenir de la soirée CRT de la Table Ronde du 26/11 à St Brieuc ! ', '', 'Photo souvenir de la soirée CRT de la Table Ronde ', 209),
('', '', '', 210),
('', '', '', 211),
('', '', '', 212),
('', '', '', 213),
('', '', '', 214),
('Photo prise au Del Arte de Ploermel', 'Del Arte', 'photo prise au Del Arte de Ploermel', 215),
('', '', '', 216),
('', '', '', 217),
('', '', '', 218),
('Photo souvenir prise au Village By CA des Côtes d\'Armor avec la borne photo Selfizee', 'selfizee, LeVillagebyCA', 'Photo souvenir prise au Village By CA des Côtes d\'Armor avec la borne photo Selfizee', 219),
('', '', '', 220),
('', '', '', 222),
('', '', '', 223),
('', '', '', 224),
('', '', '', 225),
('', '', '', 226),
('', '', '', 227),
('', '', '', 228),
('Photo souvenir prise au trail Glazig le 4/5 février 2017 ', 'glazig, trail, stbrieuc', 'Photo souvenir prise au trail Glazig ', 229),
('', '', '', 230),
('', '', '', 231),
('', '', '', 232),
('Photo souvenir de la découverte de la plateforme Breizh PR le 27 février 2017', '', 'Photo souvenir de la découverte de la plateforme Breizh PR le 27 février 2017', 233),
('', '', '', 234),
('Photo souvenir de la soirée des Oscars des entreprises des Côtes d\'Armor', 'Photo souvenir de la soirée des Oscars des entreprises des Côtes d\'Armor', '', 235),
('Job Dating Alternant Credit Agricole à Saint Brieuc le 11 mars 2017, j\'y étais !', '#jobdatingalternant #creditagricole', 'Job Dating Alternant Credit Agricole à Saint Brieuc le 11 mars 2017, j\'y étais !', 236),
('', '', '', 237),
('', '', '', 238),
('', '', '', 239),
('', '', '', 240),
('Photo souvenir prise sur le stand Triskalia lors du salon Agri Deiz 2017', '', 'Photo souvenir prise sur le stand Triskalia lors du salon Agri Deiz', 241),
('', '', '', 242),
('', '', '', 243),
('Photo souvenir soirée Facet Ingéniérie du 23 mars 2017', '', 'Photo souvenir soirée Facet Ingéniérie du 23 mars 2017', 244),
('', '', '', 245),
('Photo souvenir prise lors de l\'Assemblée Générale 2017 du Crédit Agricole des Côtes d\'Armor', '', 'Photo souvenir prise lors de l\'Assemblée Générale 2017 du Crédit Agricole des Côtes d\'Armor', 246),
('Photo souvenir prise lors de la soirée d\'inauguration du Del Arte Montpellier Castelnau le 11 avril 2017.', '', 'Photo souvenir prise lors de la soirée d\'inauguration du Del Arte Montpellier Castelnau ', 247),
('', '', '', 248),
('', '', '', 249),
('', '', '', 250),
('', '', '', 251),
('', '', '', 252),
('Photo souvenir prise lors de l\'inauguration du show room de Doré Habitat à Langueux', '', 'Photo souvenir prise lors de l\'inauguration du show room de Doré Habitat à Langueux', 253),
('Photo souvenir prise lors de la soirée 100% filles du VandB Langueux du 22 avril 2017 !', '', 'Photo souvenir prise lors de la soirée 100% filles du VandB Langueux du 22 avril 2017 !', 254),
('', '', '', 255),
('', '', '', 256),
('', '', '', 257),
('', '', '', 258),
('Photo souvenir prise lors de la Fête de la Coquille Saint-Jacques à Erquy le 15 et 16 avril 2017.', '', 'Photo souvenir de la fête de la Coquille Saint-Jacques à Erquy le 15 et 16 avril ', 259),
('', '', '', 260),
('', '#LeSpot #CréditAgricole #Nevers', 'Photo prise lors de la soirée \"Le Spot\" de Nevers', 261),
('Photo souvenir prise lors des portes ouvertes de la gare de Rennes ', '', 'Photo souvenir prise lors des portes ouvertes de la gare de Rennes ', 262),
('', '', '', 263),
('', '', '', 264),
('', '', '', 265),
('Photo souvenir offerte par l’association des commerçants du Centre Commercial Carrefour Nantes La Beaujoire pour la fête des mères.', '', 'Photo souvenir pour la fête des mères ', 266),
('', '', '', 267),
('Photo souvenir offerte par l’association des commerçants du Centre Commercial Carrefour Vannes pour son animation « Offrez une photo à votre Maman ».', '', 'Photo souvenir pour la fête des mères ', 268),
('', '', '', 269),
('', '', '', 270),
('', '', '', 271),
('', '', '', 273),
('Photo souvenir prise sur le festival Art Rock lors de la soirée FFB Côtes d\'Armor', '', 'Photo souvenir prise sur le festival Art Rock lors de la soirée FFB Côtes d\'Armor', 274),
('Photo souvenir prise lors du trail de Guerlédan le 3 et 4 juin 2017', '', 'Photo souvenir prise lors du trail de Guerlédan le 3 et 4 juin 2017', 276),
('Photo souvenir prise lors du festival Art Rock 2017 offerte par le Conseil Départemental des Côtes d\'Armor', '', 'Photo souvenir prise lors du festival Art Rock 2017', 277),
('', '', '', 278),
('Photo souvenir de la soirée FFB et club des partenaires du BTP 22 au festival Art Rock 2017 !', '', 'Photo souvenir de la soirée FFB / Art Rock ', 279),
('', '', '', 280),
('', '', '', 281),
('', '', '', 282),
('', '', '', 283),
('Photo souvenir prise lors du trail de Guerlédan le 3 et 4 juin 2017', '', 'Photo souvenir prise lors du trail de Guerlédan ', 284),
('', '', '', 285),
('', '', '', 286),
('', '', '', 287),
('', '', '', 288),
('', '', '', 289),
('', '', '', 290),
('', '', '', 291),
('', '', '', 292),
('', '', '', 293),
('', '', '', 294),
('Photo souvenir de la soirée des 40 ans Ceva Loudeac', '', 'Photo souvenir de la soirée 40 ans Ceva Loudeac', 295),
('', '', '', 296),
('', '', '', 297),
('', '', '', 298),
('', '', '', 299),
('', '', '', 300),
('', '', '', 301),
('', '', '', 302),
('', '', '', 303),
('', '', '', 304),
('', '', '', 305),
('', '', '', 306),
('', '', '', 307),
('', '', '', 308),
('', '', '', 309),
('', '', '', 310),
('Photo souvenir prise lors du Festival L\'Armor à Sons à Bobital.', 'bobital', 'Photo souvenir prise lors du Festival L\'Armor à Sons à Bobital.', 311),
('', '', '', 312),
('Photo souvenir prise lors de l\'arrivée de la ligne LGV en Gare de St-Brieuc ! ', 'passezalouest', 'Photo souvenir prise lors de l\'arrivée de la ligne LGV en Gare de St-Brieuc !', 313),
('Photo souvenir de l\'arrivée de la LGV en gare de Rennes', 'passezalouest', 'Photo souvenir de l\'arrivée de la LGV en gare de Rennes', 314),
('', '', '', 315),
('', '', '', 316),
('', '', '', 317),
('', '', '', 318),
('Souvenir de l\'anniversaire d\'Intermarché Saint-Lyphard', '', 'Souvenir de l\'anniversaire d\'Intermarché Saint-Lyphard', 319),
('', '', '', 320),
('', '', '', 321),
('', '', '', 322),
('', '', '', 323),
('', '', '', 324),
('', '', '', 325),
('Souvenir des Vieilles Charrues 2017 avec Daunat', '#daunat #charrues17 #vieillescharrues17', 'Souvenir des Vieilles Charrues 2017 avec Daunat', 326),
('', '', '', 327),
('', '', '', 328),
('Souvenir des championnats de France de VTT à Ploeuc !', '#VTT #championnatsfrancevtt #conseildépartemental22 #ploeuc', 'Souvenir des championnats de France de VTT à Ploeuc !', 329),
('', '', '', 330),
('', '', '', 331),
('', '', '', 332),
('', '', '', 333),
('', '', '', 334),
('', '', '', 335),
('', '', '', 336),
('', '', '', 337),
('', '', '', 338),
('', '', '', 339),
('', '', '', 340),
('', '', '', 341),
('', '', '', 342),
('', '', '', 343),
('', '', '', 344),
('', '', '', 345),
('', '', '', 346),
('', '', '', 347),
('', '', '', 348),
('', '', '', 349),
('', '', '', 350),
('', '', '', 351),
('', '', '', 352),
('', '', '', 353),
('', '', '', 354),
('', '', '', 355),
('', '', '', 356),
('', '', '', 357),
('', '', '', 358),
('', '', '', 359),
('', '', '', 360),
('', '', '', 361),
('', '', '', 362),
('', '', '', 363),
('', '', '', 364),
('', '', '', 365),
('', '', '', 366),
('', '', '', 367),
('', '', '', 368),
('', '', '', 369),
('', '', '', 370),
('', '', '', 371),
('', '', '', 372),
('Photo prise au SPACE à Rennes', '', 'Photo prise au SPACE à Rennes', 373),
('Photo souvenir prise lors du SPACE 2017 // Photo from the SPACE 2017 ', 'Space', 'Photo from the SPACE 2017 ', 374),
('Photo souvenir prise lors du SPACE 2017 // Photo from the SPACE 2017 ', '', 'Photo from the SPACE 2017 ', 375),
('Photo souvenir prise sur le stand de Cogedis lors du Space 2017', 'Cogedis, Space', 'Photo souvenir prise sur le stand de Cogedis lors du Space 2017', 376),
('Photo souvenir prise lors du SPACE 2017 // Photo from the SPACE 2017 ', '', 'Photo from the SPACE 2017 ', 377),
('', '', '', 378),
('', '', '', 379),
('', '', '', 381),
('', '', '', 382),
('', '', '', 383),
('', '', '', 384),
('', '', '', 385),
('', '', '', 386),
('', '', '', 387),
('', '', '', 388),
('Photo souvenir du Space avec Itek', '', 'Photo souvenir du Space avec Itek', 389),
('', '', '', 390),
('Photo souvenir de l\'inauguration du Novotel de Saint-Brieuc', '', 'Photo souvenir de l\'inauguration du Novotel de Saint-Brieuc', 391),
('', '', '', 392),
('', '', '', 393),
('', '', '', 394),
('', '', '', 395),
('', '', '', 396),
('', '', '', 397),
('Photo souvenir prise lors de la soirée anniversaire du VandB Macon', '', 'Photo souvenir prise lors de la soirée anniversaire du VandB Macon', 398),
('Photo souvenir du Space avec le Crédit Agricole', '', 'Photo souvenir du Space avec le Crédit Agricole', 399),
('Photo souvenir de la Foire de Caen avec Ouest-France', '', 'Photo souvenir de la Foire de Caen avec Ouest-France', 400),
('Photo souvenir de la foire aux vins dans votre Intermarché Plaintel', '', 'Photo souvenir de la foire aux vins dans votre Intermarché Plaintel', 401),
('', '', '', 402),
('Photo souvenir des Journées du Patrimoine avec le Conseil Départemental des Côtes d\'Armor', '', 'Photo souvenir des Journées du Patrimoine avec le Conseil Départemental des Côtes d\'Armor', 403),
('Photo souvenir prise lors de la soirée d\'inauguration du Del Arte Pacé - Rennes', 'delarte', 'Photo souvenir prise lors de la soirée d\'inauguration du Del Arte Pacé - Rennes', 404),
('', '', '', 405),
('', '', '', 406),
('Photo souvenir de l\'inauguration de votre restaurant Del Arte Albertville', '', 'Photo souvenir de l\'inauguration de votre restaurant Del Arte Albertville', 407),
('', '', '', 408),
('', '', '', 409),
('Photo souvenir des Portes Ouvertes Hue - Socoda', '', 'Photo souvenir des Portes Ouvertes Hue - Socoda', 410),
('', '', '', 411),
('', '', '', 412),
('Votre photo souvenir de La Super Coul Party - Guivarch l\'Imprimerie - Imprimerie Jacq', '', 'Votre photo souvenir de La Super Coul Party - Guivarch l\'Imprimerie - Imprimerie Jacq', 413),
('', '', '', 415),
('', '', '', 416),
('', '', '', 417),
('', '', '', 418),
('', '', '', 419),
('', '', '', 420),
('', '', '', 421),
('Photo souvenir des Portes-Ouvertes du Centre Kerval', '', 'Photo souvenir des Portes-Ouvertes du Centre Kerval', 422),
('', '', '', 423),
('Photo souvenir prise lors du salon \"Oh la Vache\" des 14 et 15 octobre 2017 sur le stand Triskalia', 'triskalia', 'Photo souvenir du salon \"Oh la Vache\" sur le stand Triskalia', 424),
('', '', '', 425),
('Photo souvenir de Meet my Village', '', 'Photo souvenir de Meet my Village', 426),
('', '', '', 427),
('Photo souvenir de l\'inauguration de 5 nouvelles enseignes au Centre Commercial Carrefour Langueux', '', 'Photo souvenir de l\'inauguration de 5 nouvelles enseignes au Centre Commercial Carrefour Langueux', 428),
('Votre photo souvenir de votre Centre Commercial Carrefour Langueux', '', 'Votre photo souvenir de votre Centre Commercial Carrefour Langueux', 429),
('Photo Souvenir de l\'Afterwork 100% filles à La Suite à Rennes', '', 'Photo Souvenir de l\'Afterwork 100% filles à La Suite à Rennes', 430),
('Photo souvenir du Marathon Vert de Rennes avec la SNCF\r\n', '', 'Photo souvenir du Marathon Vert de Rennes avec la SNCF', 431),
('', '', '', 432),
('Photo souvenir de la semaine de la rénovation avec Tanguy Matériaux', '', 'Photo souvenir de la semaine de la rénovation avec Tanguy Matériaux', 433),
('Photo souvenir de l\'inauguration du QG au Carré Rosengart', '', 'Photo souvenir de l\'inauguration du QG au Carré Rosengart', 434),
('', '', '', 435),
('Photo souvenir de l\'Innovation\'s Day avec Vinci et Selfizee', '', 'Photo souvenir de l\'Innovation\'s Day avec Vinci et Selfizee', 436),
('Photo souvenir Initiative - Pays de Morlaix', '', 'Photo souvenir Initiative - Pays de Morlaix', 437),
('Photo souvenir de l\'inauguration du restaurant Del Arte à Arles', '', 'Photo souvenir de l\'inauguration du restaurant Del Arte à Arles', 438),
('Photo souvenir de la soirée After Holidays au Novotel Rennes Centre Gare', '', 'Photo souvenir de la soirée After Holidays au Novotel Rennes Centre Gare', 439),
('Photo Souvenir de la Soirée Open Manager 35 à Rennes School of Business', '', 'Photo Souvenir de la Soirée Open Manager 35 à Rennes School of Business', 440),
('Photo Souvenir du Start-up Week-end à Saint-Brieuc', '', 'Photo Souvenir du Start-up Week-end à Saint-Brieuc', 441),
('#15ANSREB Photo souvenir de l\'AG des 15 ans de Réseau Entreprendre Bretagne ', '#15ANSREB', 'Photo souvenir de l\'AG des 15 ans de Réseau Entreprendre Bretagne ', 442),
('Photo souvenir de Meet Pro Bretagne avec Selfizee', '#selfizee', 'Photo souvenir de Meet Pro Bretagne avec Selfizee', 443),
('Votre photo souvenir de l\'inauguration de la Fnac Saint-Brieuc C.C. Les Champs', '', 'Votre photo souvenir de l\'inauguration de la Fnac Saint-Brieuc C.C. Les Champs', 444),
('Photo souvenir des Assises de l\'économie de la Mer au Havre les 21 et 22 novembre 2017', '', 'Photo souvenir des Assises de l\'économie de la Mer au Havre les 21 et 22 novembre 2017', 445),
('Photo souvenir de la soirée de l\'ESG Rennes', '', 'Photo souvenir de la soirée de l\'ESG Rennes', 446),
('', '', '', 447),
('', '', '', 448),
('', '', '', 449),
('Photo souvenir avec Enedis', '', 'Photo souvenir avec Enedis', 450),
('', '', '', 451),
('Photo souvenir des Assises de l\'économie de la Mer au Havre les 21 et 22 novembre 2017', '', 'Photo souvenir des Assises de l\'économie de la Mer au Havre les 21 et 22 novembre 2017', 452),
('', '', '', 453),
('', '', '', 454),
('', '', '', 455),
('Photo souvenir de la 9e plénière PLATO BRETAGNE à Carhaix', '', 'Photo souvenir de la 9e plénière PLATO BRETAGNE à Carhaix', 456),
('Photo souvenir du Salon de l\'Habitat à Pontivy', '', 'Photo souvenir du Salon de l\'Habitat à Pontivy', 458),
('Photo souvenir de l\'inauguration de Volvo Saint-Brieuc', '', 'Photo souvenir de l\'inauguration de Volvo Saint-Brieuc', 459),
('Photo souvenir de la Sainte-Barbe à la caserne du Perray à Yffiniac', '', 'Photo souvenir de la Sainte-Barbe à la caserne du Perray à Yffiniac', 460),
('Photo souvenir de Noël à la centrale avec EDF à Cordemais', '', 'Photo souvenir de Noël à la centrale avec EDF à Cordemais', 461),
('Photo Souvenir des 10 ans du V&B La Flèche', '', 'Photo Souvenir des 10 ans du V&B La Flèche', 462),
('Photo souvenir des 3 ans du V&B Chalon Sur Saone', '', 'Photo souvenir des 3 ans du V&B Chalon Sur Saone', 463),
('', '', '', 464),
('Photo souvenir de la réouverture de la ligne SNCF Brest - Quimper à la gare de Châteaulin', '', 'Photo souvenir de la réouverture de la ligne SNCF Brest - Quimper à la gare de Châteaulin', 465),
('', '', '', 466),
('', '', '', 467),
('', '', '', 468),
('', '', '', 469),
('Photo souvenir de la soirée Daucy à Locminé', '', 'Photo souvenir de la soirée Daucy à Locminé', 470),
('Photo souvenir du Goûter de Noël de l\'APEL Sainte-Anne Pordic', '', 'Photo souvenir du Goûter de Noël de l\'APEL Sainte-Anne Pordic', 471),
('Photo souvenir de Noël en Lumières avec la mairie d\'Albertville', '', 'Photo souvenir de Noël en Lumières avec la mairie d\'Albertville', 472),
('Photo souvenir du Blitz Day Microsoft 365 @LDLC.pro', '', 'Photo souvenir du Blitz Day Microsoft 365 @LDLC.pro', 473),
('Photo souvenir de la soirée comité d\'entreprise Atlantic Automobiles et Felix Faure Automobiles', '', 'Photo souvenir de la soirée comité d\'entreprise Atlantic Automobiles et Felix Faure Automobiles', 474),
('', '', '', 475),
('', '', '', 476),
('', '', '', 477),
('Photo souvenir de la soirée de Gala ESUP Rennes au Roahzon Park', '', 'Photo souvenir de la soirée de Gala ESUP Rennes au Roahzon Park', 478),
('', '', '', 479),
('', '', '', 480),
('Photo souvenir du nouvel an au Kasino de Saint-Quay-Portrieux', '', 'Photo souvenir du nouvel an au Kasino de Saint-Quay-Portrieux', 481),
('Photo souvenir du nouvel an Kasino de Perros-Guirec', '', 'Photo souvenir du nouvel an Kasino de Perros-Guirec', 482),
('Photo souvenir du Nouvel An au Moulin de Lanrodec by Traiteur Mallet', '', 'Photo souvenir du Nouvel An au Moulin de Lanrodec by Traiteur Mallet', 483),
('Photo souvenir de la soirée des voeux de la ville de Lannion', '', 'Photo souvenir de la soirée des voeux de la ville de Lannion', 484),
('Photo souvenir de la réunion du personnel Crédit Agricole Centre Loire du 11 janvier 2018 à Bourges', '', 'Photo souvenir de la réunion du personnel Crédit Agricole Centre Loire du 11 janvier 2018 à Bourges', 485),
('', '', '', 486),
('Photo souvenir des voeux de la Mairie de Lannion', '', 'Photo souvenir des voeux de la Mairie de Lannion', 487),
('Photo souvenir de la soirée Valeor !', '', 'Photo souvenir de la soirée Valeor !', 488),
('', '', '', 489),
('Photo souvenir de la Maison Yves Rocher', '', 'Photo souvenir de la Maison Yves Rocher', 490),
('', '', '', 491),
('Photo souvenir de la soirée des voeux Blot Immobilier', '', 'Photo souvenir de la soirée des voeux Blot Immobilier', 492),
('', '', '', 493),
('', '', '', 494),
('', '', '', 495),
('', '', '', 496),
('#FANZONEGROUPAMA', '#FANZONEGROUPAMA', '', 497),
('Photo souvenir de la soirée I wish au Village by CA 35', '', 'Photo souvenir de la soirée I wish au Village by CA 35', 498),
('', '', '', 499),
('The French Tech booth at CES 2018', '', 'The French Tech booth at CES 2018', 500),
('Photo souvenir de la convention annuelle Square Habitat', '', 'Photo souvenir de la convention annuelle Square Habitat', 501),
('Souvenir des 50 ans des Jeux Olympiques à Grenoble ', '', 'Souvenir des 50 ans des Jeux Olympiques à Grenoble ', 502),
('Vidéo souvenir lors du passage au Festival Olympique à Grenoble ', '', 'Vidéo souvenir lors du passage aux 50 ans des Jeux Olympiques à Grenoble', 503),
('', '', '', 504),
('Photo souvenir prise lors de la journée Banque Populaire \"Let\'s go !\" - le 15 février 2018 à Nantes ', '', 'Photo souvenir prise lors de la journée Banque Populaire - Let\'s Go !', 505),
('', '', '', 506),
('', '', '', 507),
('Photo souvenir du salon du tourisme au stand \"Tout Vivre en Côtes d\'Armor\"', '', 'Photo souvenir du salon du tourisme au stand \"Tout Vivre en Côtes d\'Armor\"', 508),
('', '', '', 509),
('Photo souvenir de l\'AG Produit En Bretagne', '', 'Photo souvenir de l\'AG Produit En Bretagne', 510),
('Votre photo souvenir de Grand Ouest Innovation', '', 'Votre photo souvenir de Grand Ouest Innovation', 511),
('Photo souvenir de la soirée Chippendales au Casino de Saint-Quay-Portrieux', '', 'Photo souvenir de la soirée Chippendales au Casino de Saint-Quay-Portrieux', 512),
('', '', '', 513),
('', '', '', 514),
('Photo souvenir #TeamBonoboJeanVert', '', 'Photo souvenir #TeamBonoboJeanVert', 515),
('', '', '', 516),
('', '#FanZoneGroupama', '', 517),
('', '', '', 518),
('', '', '', 519),
('', '', '', 523),
('Photo souvenir de la semaine au GEM Altigliss Challenge offerte par Selfizee !', 'selfizee', 'Photo souvenir de la semaine au GEM Altigliss Challenge ', 524),
('Photo souvenir de l\'édition Sportem 2018 @ Paris - parc des Princes via la borne photo Selfizee \r\n\r\n', 'selfizee, sportem', 'Photo souvenir de l\'édition Sportem 2018 @ Paris - parc des Princes via la borne photo Selfizee ', 525),
('', '', '', 526),
('', '', '', 527),
('', '', '', 528),
('', '', '', 529),
('', '', '', 530),
('', '', '', 532),
('', '', '', 533),
('', '', '', 534),
('', '', '', 536),
('', '', '', 537),
('', '', '', 538),
('', '', '', 539),
('', '', '', 540),
('', '', '', 541),
('', '', '', 542),
('', '', '', 543),
('', '', '', 544),
('', '', '', 546),
('', '', '', 547),
('', '', '', 548),
('', '', '', 549),
('', '', '', 550),
('DC COMICS EXPERIENCE', '', 'Photo DC COMICS EXPERIENCE', 551),
('', '', '', 552),
('', '', '', 553),
('', '', '', 554),
('', '', '', 555),
('', '', '', 556),
('Photo souvenir du 2ème anniversaire de l\'Avenue 83 à Toulon.\r\n', '', 'Photo souvenir du 2ème anniversaire de l\'Avenue 83 à Toulon', 557),
('', '', '', 558),
('', '', '', 559),
('', '', '', 560),
('', '', '', 561),
('Photo prise lors de l\'édition 2018 de Landes & Bruyères à Erquy', '', 'Photo prise lors de l\'édition de Landes & Bruyères à Erquy', 562),
('', '', '', 563),
('', '', '', 564),
('', '', '', 565),
('', '', '', 567),
('', '', '', 568),
('', '', '', 569),
('', '', '', 570),
('', '', '', 571),
('', '', '', 572),
('', '', '', 573),
('Photo souvenir prise lors de l\'inauguration du Del Arte de Salaise-sur-Sanne', '', 'Photo souvenir prise lors de l\'inauguration du Del Arte de Salaise-sur-Sanne', 574),
('', '', '', 575),
('', '', '', 576),
('', '', '', 577),
('', '', '', 578),
('', '', '', 579),
('', '', '', 580),
('', '', '', 581),
('', '', '', 582),
('', '', '', 583),
('', '', '', 584),
('', '', '', 585),
('', '', '', 586),
('', '', '', 587),
('', '', '', 588),
('', '', '', 589),
('', '', '', 590),
('Photo souvenir prise lors du Trail des KAOS', '', '', 591),
('', '', '', 592),
('', '', '', 593),
('', '', '', 594),
('', '', '', 595),
('', '', '', 596),
('', '', '', 597),
('', '', '', 598),
('', '', '', 599),
('Photo souvenir prise lors des Terralies offerte par Cerfrance Côtes d\'Armor', '', 'Photo souvenir prise lors des Terralies offerte par Cerfrance Côtes d\'Armor', 600),
('', '', '', 601),
('Photo Souvenir Art Rock 2018 offert par le Conseil Départemental des Côtes d\'Armor', 'artrock', 'Photo Souvenir Art Rock 2018 offert par le Conseil Départemental des Côtes d\'Armor', 602),
('', '', '', 603),
('Soirée Soooo Gatsby !', '', 'Soirée Soooo Gatsby !', 604),
('', '', '', 605),
('Photo souvenir prise lors du passage au stand Silverwood lors du Carrefour International du Bois.', '', 'Photo souvenir prise lors du passage au stand Silverwood lors du Carrefour International du Bois.', 606),
('', '', '', 607),
('', '', '', 608),
('', '', '', 609),
('', '', '', 610),
('', '', '', 611),
('Votre photo souvenir de l\'événement Groupama au Hockey Club Dinan Quévert', '', '', 612),
('Voici la photo de l’événement Fun Breizh', '', '', 613),
('', '', '', 614),
('', '', '', 615),
('Votre photo de l’événement ! ', '', '', 616),
('', '', '', 617),
('', '', '', 618),
('', '', '', 619),
('', '', '', 620),
('', '', '', 621),
('', '', '', 622),
('', '', '', 623),
('', '', '', 624),
('', '', '', 625),
('', '', '', 626),
('', '', '', 627),
('', '', '', 630),
('', '', '', 631),
('', '', '', 632),
('', '', '', 633),
('', '', '', 634),
('', '', '', 635),
('', '', '', 636),
('', '', '', 637),
('Photo souvenir aux bulles du 23 !', '', 'Photo souvenir aux bulles du 23 !', 638),
('', '', '', 639),
('', '', '', 640),
('', '', '', 641),
('', '', '', 642),
('', '', '', 644),
('', '', '', 645),
('Photo souvenir lors du RHDay Arkéa', '', 'Photo souvenir lors du RHDay Arkéa', 646),
('', '', '', 647),
('', '', '', 648),
('Souvenir photo des 30 ans de SOVAMEP', '', 'Souvenir photo des 30 ans de SOVAMEP', 649),
('', '', '', 650),
('', '', '', 651),
('', '', '', 653),
('', '', '', 654),
('', '', '', 655),
('', '', '', 656),
('', '', '', 657),
('', '', '', 658),
('', '', '', 659),
('', '', '', 660),
('', '', '', 661),
('', '', '', 662),
('', '', '', 663),
('', '', '', 664),
('', '', '', 665),
('', '', '', 666),
('', '', '', 667),
('', '', '', 668),
('', '', '', 669),
('', '', '', 670),
('', '', '', 671),
('', '', '', 672),
('', '', '', 673),
('', '', '', 674),
('', '', '', 675),
('', '', '', 676),
('', '', '', 677),
('', '', '', 678),
('', '', '', 680),
('', '', '', 681),
('', '', '', 682),
('', '', '', 683),
('', '', '', 684),
('', '', '', 685),
('', '', '', 686),
('', '', '', 688),
('', '', '', 689),
('', '', '', 690),
('', '', '', 691),
('', '', '', 692),
('', '', '', 693),
('', '', '', 695),
('', '', '', 696),
('', '', '', 697),
('', '', '', 698),
('', '', '', 699),
('', '', '', 701),
('', '', '', 702),
('Photo souvenir prise lors du Défi Sport et Nature aux Domaine des Ormes', '', '', 720),
('', '', '', 843);


